packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js
  - core-js-pure
  - electron
  - electron-winstaller
  - unrs-resolver
